/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlusRouteImport } from './routes/plus'
import { Route as OtecRouteImport } from './routes/otec'
import { Route as CrecimientoRouteImport } from './routes/crecimiento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlusIndexRouteImport } from './routes/plus/index'
import { Route as OtecIndexRouteImport } from './routes/otec/index'
import { Route as CrecimientoIndexRouteImport } from './routes/crecimiento/index'
import { Route as PlusNosotrosRouteImport } from './routes/plus/nosotros'
import { Route as OtecNosotrosRouteImport } from './routes/otec/nosotros'
import { Route as OtecGaleriaRouteImport } from './routes/otec/galeria'
import { Route as OtecCotizacionRouteImport } from './routes/otec/cotizacion'
import { Route as OtecContactoRouteImport } from './routes/otec/contacto'
import { Route as CrecimientoNosotrosRouteImport } from './routes/crecimiento/nosotros'
import { Route as CrecimientoGaleriaRouteImport } from './routes/crecimiento/galeria'
import { Route as CrecimientoCotizacionRouteImport } from './routes/crecimiento/cotizacion'
import { Route as OtecCursosIndexRouteImport } from './routes/otec/cursos/index'
import { Route as CrecimientoTalleresIndexRouteImport } from './routes/crecimiento/talleres/index'
import { Route as PlusProductosProductIdRouteImport } from './routes/plus/productos/$productId'
import { Route as OtecCursosCourseSlugRouteImport } from './routes/otec/cursos/$courseSlug'
import { Route as CrecimientoTalleresSlugRouteImport } from './routes/crecimiento/talleres/$slug'

const PlusRoute = PlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => rootRouteImport,
} as any)
const OtecRoute = OtecRouteImport.update({
  id: '/otec',
  path: '/otec',
  getParentRoute: () => rootRouteImport,
} as any)
const CrecimientoRoute = CrecimientoRouteImport.update({
  id: '/crecimiento',
  path: '/crecimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlusIndexRoute = PlusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlusRoute,
} as any)
const OtecIndexRoute = OtecIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OtecRoute,
} as any)
const CrecimientoIndexRoute = CrecimientoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrecimientoRoute,
} as any)
const PlusNosotrosRoute = PlusNosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => PlusRoute,
} as any)
const OtecNosotrosRoute = OtecNosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => OtecRoute,
} as any)
const OtecGaleriaRoute = OtecGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => OtecRoute,
} as any)
const OtecCotizacionRoute = OtecCotizacionRouteImport.update({
  id: '/cotizacion',
  path: '/cotizacion',
  getParentRoute: () => OtecRoute,
} as any)
const OtecContactoRoute = OtecContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => OtecRoute,
} as any)
const CrecimientoNosotrosRoute = CrecimientoNosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => CrecimientoRoute,
} as any)
const CrecimientoGaleriaRoute = CrecimientoGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => CrecimientoRoute,
} as any)
const CrecimientoCotizacionRoute = CrecimientoCotizacionRouteImport.update({
  id: '/cotizacion',
  path: '/cotizacion',
  getParentRoute: () => CrecimientoRoute,
} as any)
const OtecCursosIndexRoute = OtecCursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => OtecRoute,
} as any)
const CrecimientoTalleresIndexRoute =
  CrecimientoTalleresIndexRouteImport.update({
    id: '/talleres/',
    path: '/talleres/',
    getParentRoute: () => CrecimientoRoute,
  } as any)
const PlusProductosProductIdRoute = PlusProductosProductIdRouteImport.update({
  id: '/productos/$productId',
  path: '/productos/$productId',
  getParentRoute: () => PlusRoute,
} as any)
const OtecCursosCourseSlugRoute = OtecCursosCourseSlugRouteImport.update({
  id: '/cursos/$courseSlug',
  path: '/cursos/$courseSlug',
  getParentRoute: () => OtecRoute,
} as any)
const CrecimientoTalleresSlugRoute = CrecimientoTalleresSlugRouteImport.update({
  id: '/talleres/$slug',
  path: '/talleres/$slug',
  getParentRoute: () => CrecimientoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crecimiento': typeof CrecimientoRouteWithChildren
  '/otec': typeof OtecRouteWithChildren
  '/plus': typeof PlusRouteWithChildren
  '/crecimiento/cotizacion': typeof CrecimientoCotizacionRoute
  '/crecimiento/galeria': typeof CrecimientoGaleriaRoute
  '/crecimiento/nosotros': typeof CrecimientoNosotrosRoute
  '/otec/contacto': typeof OtecContactoRoute
  '/otec/cotizacion': typeof OtecCotizacionRoute
  '/otec/galeria': typeof OtecGaleriaRoute
  '/otec/nosotros': typeof OtecNosotrosRoute
  '/plus/nosotros': typeof PlusNosotrosRoute
  '/crecimiento/': typeof CrecimientoIndexRoute
  '/otec/': typeof OtecIndexRoute
  '/plus/': typeof PlusIndexRoute
  '/crecimiento/talleres/$slug': typeof CrecimientoTalleresSlugRoute
  '/otec/cursos/$courseSlug': typeof OtecCursosCourseSlugRoute
  '/plus/productos/$productId': typeof PlusProductosProductIdRoute
  '/crecimiento/talleres': typeof CrecimientoTalleresIndexRoute
  '/otec/cursos': typeof OtecCursosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crecimiento/cotizacion': typeof CrecimientoCotizacionRoute
  '/crecimiento/galeria': typeof CrecimientoGaleriaRoute
  '/crecimiento/nosotros': typeof CrecimientoNosotrosRoute
  '/otec/contacto': typeof OtecContactoRoute
  '/otec/cotizacion': typeof OtecCotizacionRoute
  '/otec/galeria': typeof OtecGaleriaRoute
  '/otec/nosotros': typeof OtecNosotrosRoute
  '/plus/nosotros': typeof PlusNosotrosRoute
  '/crecimiento': typeof CrecimientoIndexRoute
  '/otec': typeof OtecIndexRoute
  '/plus': typeof PlusIndexRoute
  '/crecimiento/talleres/$slug': typeof CrecimientoTalleresSlugRoute
  '/otec/cursos/$courseSlug': typeof OtecCursosCourseSlugRoute
  '/plus/productos/$productId': typeof PlusProductosProductIdRoute
  '/crecimiento/talleres': typeof CrecimientoTalleresIndexRoute
  '/otec/cursos': typeof OtecCursosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crecimiento': typeof CrecimientoRouteWithChildren
  '/otec': typeof OtecRouteWithChildren
  '/plus': typeof PlusRouteWithChildren
  '/crecimiento/cotizacion': typeof CrecimientoCotizacionRoute
  '/crecimiento/galeria': typeof CrecimientoGaleriaRoute
  '/crecimiento/nosotros': typeof CrecimientoNosotrosRoute
  '/otec/contacto': typeof OtecContactoRoute
  '/otec/cotizacion': typeof OtecCotizacionRoute
  '/otec/galeria': typeof OtecGaleriaRoute
  '/otec/nosotros': typeof OtecNosotrosRoute
  '/plus/nosotros': typeof PlusNosotrosRoute
  '/crecimiento/': typeof CrecimientoIndexRoute
  '/otec/': typeof OtecIndexRoute
  '/plus/': typeof PlusIndexRoute
  '/crecimiento/talleres/$slug': typeof CrecimientoTalleresSlugRoute
  '/otec/cursos/$courseSlug': typeof OtecCursosCourseSlugRoute
  '/plus/productos/$productId': typeof PlusProductosProductIdRoute
  '/crecimiento/talleres/': typeof CrecimientoTalleresIndexRoute
  '/otec/cursos/': typeof OtecCursosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crecimiento'
    | '/otec'
    | '/plus'
    | '/crecimiento/cotizacion'
    | '/crecimiento/galeria'
    | '/crecimiento/nosotros'
    | '/otec/contacto'
    | '/otec/cotizacion'
    | '/otec/galeria'
    | '/otec/nosotros'
    | '/plus/nosotros'
    | '/crecimiento/'
    | '/otec/'
    | '/plus/'
    | '/crecimiento/talleres/$slug'
    | '/otec/cursos/$courseSlug'
    | '/plus/productos/$productId'
    | '/crecimiento/talleres'
    | '/otec/cursos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crecimiento/cotizacion'
    | '/crecimiento/galeria'
    | '/crecimiento/nosotros'
    | '/otec/contacto'
    | '/otec/cotizacion'
    | '/otec/galeria'
    | '/otec/nosotros'
    | '/plus/nosotros'
    | '/crecimiento'
    | '/otec'
    | '/plus'
    | '/crecimiento/talleres/$slug'
    | '/otec/cursos/$courseSlug'
    | '/plus/productos/$productId'
    | '/crecimiento/talleres'
    | '/otec/cursos'
  id:
    | '__root__'
    | '/'
    | '/crecimiento'
    | '/otec'
    | '/plus'
    | '/crecimiento/cotizacion'
    | '/crecimiento/galeria'
    | '/crecimiento/nosotros'
    | '/otec/contacto'
    | '/otec/cotizacion'
    | '/otec/galeria'
    | '/otec/nosotros'
    | '/plus/nosotros'
    | '/crecimiento/'
    | '/otec/'
    | '/plus/'
    | '/crecimiento/talleres/$slug'
    | '/otec/cursos/$courseSlug'
    | '/plus/productos/$productId'
    | '/crecimiento/talleres/'
    | '/otec/cursos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrecimientoRoute: typeof CrecimientoRouteWithChildren
  OtecRoute: typeof OtecRouteWithChildren
  PlusRoute: typeof PlusRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plus': {
      id: '/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof PlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otec': {
      id: '/otec'
      path: '/otec'
      fullPath: '/otec'
      preLoaderRoute: typeof OtecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crecimiento': {
      id: '/crecimiento'
      path: '/crecimiento'
      fullPath: '/crecimiento'
      preLoaderRoute: typeof CrecimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus/': {
      id: '/plus/'
      path: '/'
      fullPath: '/plus/'
      preLoaderRoute: typeof PlusIndexRouteImport
      parentRoute: typeof PlusRoute
    }
    '/otec/': {
      id: '/otec/'
      path: '/'
      fullPath: '/otec/'
      preLoaderRoute: typeof OtecIndexRouteImport
      parentRoute: typeof OtecRoute
    }
    '/crecimiento/': {
      id: '/crecimiento/'
      path: '/'
      fullPath: '/crecimiento/'
      preLoaderRoute: typeof CrecimientoIndexRouteImport
      parentRoute: typeof CrecimientoRoute
    }
    '/plus/nosotros': {
      id: '/plus/nosotros'
      path: '/nosotros'
      fullPath: '/plus/nosotros'
      preLoaderRoute: typeof PlusNosotrosRouteImport
      parentRoute: typeof PlusRoute
    }
    '/otec/nosotros': {
      id: '/otec/nosotros'
      path: '/nosotros'
      fullPath: '/otec/nosotros'
      preLoaderRoute: typeof OtecNosotrosRouteImport
      parentRoute: typeof OtecRoute
    }
    '/otec/galeria': {
      id: '/otec/galeria'
      path: '/galeria'
      fullPath: '/otec/galeria'
      preLoaderRoute: typeof OtecGaleriaRouteImport
      parentRoute: typeof OtecRoute
    }
    '/otec/cotizacion': {
      id: '/otec/cotizacion'
      path: '/cotizacion'
      fullPath: '/otec/cotizacion'
      preLoaderRoute: typeof OtecCotizacionRouteImport
      parentRoute: typeof OtecRoute
    }
    '/otec/contacto': {
      id: '/otec/contacto'
      path: '/contacto'
      fullPath: '/otec/contacto'
      preLoaderRoute: typeof OtecContactoRouteImport
      parentRoute: typeof OtecRoute
    }
    '/crecimiento/nosotros': {
      id: '/crecimiento/nosotros'
      path: '/nosotros'
      fullPath: '/crecimiento/nosotros'
      preLoaderRoute: typeof CrecimientoNosotrosRouteImport
      parentRoute: typeof CrecimientoRoute
    }
    '/crecimiento/galeria': {
      id: '/crecimiento/galeria'
      path: '/galeria'
      fullPath: '/crecimiento/galeria'
      preLoaderRoute: typeof CrecimientoGaleriaRouteImport
      parentRoute: typeof CrecimientoRoute
    }
    '/crecimiento/cotizacion': {
      id: '/crecimiento/cotizacion'
      path: '/cotizacion'
      fullPath: '/crecimiento/cotizacion'
      preLoaderRoute: typeof CrecimientoCotizacionRouteImport
      parentRoute: typeof CrecimientoRoute
    }
    '/otec/cursos/': {
      id: '/otec/cursos/'
      path: '/cursos'
      fullPath: '/otec/cursos'
      preLoaderRoute: typeof OtecCursosIndexRouteImport
      parentRoute: typeof OtecRoute
    }
    '/crecimiento/talleres/': {
      id: '/crecimiento/talleres/'
      path: '/talleres'
      fullPath: '/crecimiento/talleres'
      preLoaderRoute: typeof CrecimientoTalleresIndexRouteImport
      parentRoute: typeof CrecimientoRoute
    }
    '/plus/productos/$productId': {
      id: '/plus/productos/$productId'
      path: '/productos/$productId'
      fullPath: '/plus/productos/$productId'
      preLoaderRoute: typeof PlusProductosProductIdRouteImport
      parentRoute: typeof PlusRoute
    }
    '/otec/cursos/$courseSlug': {
      id: '/otec/cursos/$courseSlug'
      path: '/cursos/$courseSlug'
      fullPath: '/otec/cursos/$courseSlug'
      preLoaderRoute: typeof OtecCursosCourseSlugRouteImport
      parentRoute: typeof OtecRoute
    }
    '/crecimiento/talleres/$slug': {
      id: '/crecimiento/talleres/$slug'
      path: '/talleres/$slug'
      fullPath: '/crecimiento/talleres/$slug'
      preLoaderRoute: typeof CrecimientoTalleresSlugRouteImport
      parentRoute: typeof CrecimientoRoute
    }
  }
}

interface CrecimientoRouteChildren {
  CrecimientoCotizacionRoute: typeof CrecimientoCotizacionRoute
  CrecimientoGaleriaRoute: typeof CrecimientoGaleriaRoute
  CrecimientoNosotrosRoute: typeof CrecimientoNosotrosRoute
  CrecimientoIndexRoute: typeof CrecimientoIndexRoute
  CrecimientoTalleresSlugRoute: typeof CrecimientoTalleresSlugRoute
  CrecimientoTalleresIndexRoute: typeof CrecimientoTalleresIndexRoute
}

const CrecimientoRouteChildren: CrecimientoRouteChildren = {
  CrecimientoCotizacionRoute: CrecimientoCotizacionRoute,
  CrecimientoGaleriaRoute: CrecimientoGaleriaRoute,
  CrecimientoNosotrosRoute: CrecimientoNosotrosRoute,
  CrecimientoIndexRoute: CrecimientoIndexRoute,
  CrecimientoTalleresSlugRoute: CrecimientoTalleresSlugRoute,
  CrecimientoTalleresIndexRoute: CrecimientoTalleresIndexRoute,
}

const CrecimientoRouteWithChildren = CrecimientoRoute._addFileChildren(
  CrecimientoRouteChildren,
)

interface OtecRouteChildren {
  OtecContactoRoute: typeof OtecContactoRoute
  OtecCotizacionRoute: typeof OtecCotizacionRoute
  OtecGaleriaRoute: typeof OtecGaleriaRoute
  OtecNosotrosRoute: typeof OtecNosotrosRoute
  OtecIndexRoute: typeof OtecIndexRoute
  OtecCursosCourseSlugRoute: typeof OtecCursosCourseSlugRoute
  OtecCursosIndexRoute: typeof OtecCursosIndexRoute
}

const OtecRouteChildren: OtecRouteChildren = {
  OtecContactoRoute: OtecContactoRoute,
  OtecCotizacionRoute: OtecCotizacionRoute,
  OtecGaleriaRoute: OtecGaleriaRoute,
  OtecNosotrosRoute: OtecNosotrosRoute,
  OtecIndexRoute: OtecIndexRoute,
  OtecCursosCourseSlugRoute: OtecCursosCourseSlugRoute,
  OtecCursosIndexRoute: OtecCursosIndexRoute,
}

const OtecRouteWithChildren = OtecRoute._addFileChildren(OtecRouteChildren)

interface PlusRouteChildren {
  PlusNosotrosRoute: typeof PlusNosotrosRoute
  PlusIndexRoute: typeof PlusIndexRoute
  PlusProductosProductIdRoute: typeof PlusProductosProductIdRoute
}

const PlusRouteChildren: PlusRouteChildren = {
  PlusNosotrosRoute: PlusNosotrosRoute,
  PlusIndexRoute: PlusIndexRoute,
  PlusProductosProductIdRoute: PlusProductosProductIdRoute,
}

const PlusRouteWithChildren = PlusRoute._addFileChildren(PlusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrecimientoRoute: CrecimientoRouteWithChildren,
  OtecRoute: OtecRouteWithChildren,
  PlusRoute: PlusRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
